name: Build and deploy on push

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          BUILD_FLAGS: --drafts
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
